services:
  postgres:
    container_name: postgres
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "book-manager"
    networks:
      ruby-network:
        ipv4_address: 172.20.0.5
  ec-ruby:
    container_name: ruby
    environment:
      - TZ="Asia/Tokyo"
    depends_on:
      - postgres
    build: .
    volumes:
      - ./:/app
    entrypoint: ["tail", "-f", "/dev/null"]
    networks:
      ruby-network:
        ipv4_address: 172.20.0.3

networks:
  ruby-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

