services:
  ec-ruby:
    container_name: ruby
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ../:/app
    entrypoint: ["tail", "-f", "/dev/null"]